import { useState, useEffect, KeyboardEvent } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import toast from 'react-hot-toast';
import api from '../utils/api';
import { useAuth } from '../context/AuthContext';

interface FollowUp {
  question: string;
  response: string;
}

interface Props {
  queryId: string | null;
  question: string;
  subject: string;
  response: string;
  initialBookmarked?: boolean;
  initialRating?: number | null;
  onDelete?: (id: string) => void;
  showDelete?: boolean;
  isNew?: boolean;
}

export default function ResponseCard({
  queryId,
  question,
  subject,
  response,
  initialBookmarked = false,
  initialRating = null,
  onDelete,
  showDelete = false,
  isNew = false,
}: Props) {
  const { user } = useAuth();
  const [bookmarked, setBookmarked]         = useState(initialBookmarked);
  const [rating, setRating]                 = useState<number | null>(initialRating);
  const [loadingBookmark, setLoadingBookmark] = useState(false);
  const [deleted, setDeleted]               = useState(false);
  const [deleting, setDeleting]             = useState(false);
  const [copied, setCopied]                 = useState(false);
  const [shared, setShared]                 = useState(false);

  // Animation states
  const [starSpinning, setStarSpinning]     = useState(false);
  const [animatingRating, setAnimatingRating] = useState<number | null>(null);
  const [showSavedBadge, setShowSavedBadge] = useState(!!queryId && isNew);

  // Follow-up state
  const [followUps, setFollowUps]           = useState<FollowUp[]>([]);
  const [followUpInput, setFollowUpInput]   = useState('');
  const [loadingFollowUp, setLoadingFollowUp] = useState(false);
  const [followUpError, setFollowUpError]   = useState<string | null>(null);

  // Auto-hide saved badge
  useEffect(() => {
    if (!showSavedBadge) return;
    const t = setTimeout(() => setShowSavedBadge(false), 2800);
    return () => clearTimeout(t);
  }, []);

  if (deleted) return null;

  // ── Utility handlers ────────────────────────────────────────────

  const handleCopy = async () => {
    await navigator.clipboard.writeText(response);
    toast.success('Answer copied to clipboard');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    const shareText = `Q: ${question}\nSubject: ${subject}\n\n${response}\n\n— Generated by StudyGenie`;
    await navigator.clipboard.writeText(shareText);
    toast.success('Copied to share!');
    setShared(true);
    setTimeout(() => setShared(false), 2000);
  };

  const handleDownload = () => {
    const slug = question.split(/\s+/).slice(0, 5).join('_').replace(/[^a-zA-Z0-9_]/g, '');
    const filename = `StudyGenie_${subject}_${slug}.txt`;
    const date = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
    const content = [
      `StudyGenie – AI Based Student Doubt Solving System`,
      `${'─'.repeat(50)}`,
      `Date:    ${date}`,
      `Subject: ${subject}`,
      ``,
      `QUESTION`,
      `${'─'.repeat(50)}`,
      question,
      ``,
      `ANSWER`,
      `${'─'.repeat(50)}`,
      response,
      ``,
      `${'─'.repeat(50)}`,
      `Generated by StudyGenie`,
    ].join('\n');
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
    toast.success('Downloaded!');
  };

  // ── Follow-up handlers ───────────────────────────────────────────

  const buildContext = () => {
    let ctx = `Original Question: ${question}\nOriginal Answer: ${response}`;
    followUps.forEach((fu, i) => {
      ctx += `\n\nFollow-up ${i + 1}: ${fu.question}\nAnswer: ${fu.response}`;
    });
    return ctx;
  };

  const handleFollowUp = async () => {
    const trimmed = followUpInput.trim();
    if (!trimmed) return;
    setLoadingFollowUp(true);
    setFollowUpError(null);
    try {
      const res = await api.post('/query/ask', { question: trimmed, subject, context: buildContext() });
      setFollowUps((prev) => [...prev, { question: trimmed, response: res.data.response }]);
      setFollowUpInput('');
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message || 'Failed to get follow-up answer';
      setFollowUpError(msg);
      toast.error(msg);
    } finally {
      setLoadingFollowUp(false);
    }
  };

  const handleFollowUpKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleFollowUp(); }
  };

  // ── Bookmark / Rate / Delete ─────────────────────────────────────

  const handleBookmark = async () => {
    if (!user || !queryId) return toast.error('Login to bookmark responses');
    const prev = bookmarked;
    setBookmarked(!bookmarked);
    setLoadingBookmark(true);
    try {
      const res = await api.patch(`/query/${queryId}/bookmark`);
      setBookmarked(res.data.isBookmarked);
      if (res.data.isBookmarked) {
        setStarSpinning(true);
        setTimeout(() => setStarSpinning(false), 500);
      }
      toast.success(res.data.isBookmarked ? 'Bookmarked!' : 'Bookmark removed');
    } catch {
      setBookmarked(prev);
      toast.error('Failed to update bookmark');
    } finally {
      setLoadingBookmark(false);
    }
  };

  const handleRate = async (stars: number) => {
    if (!user || !queryId) return toast.error('Login to rate responses');
    try {
      await api.patch(`/query/${queryId}/rate`, { rating: stars });
      setRating(stars);
      // Cascade star fill animation
      setAnimatingRating(stars);
      setTimeout(() => setAnimatingRating(null), stars * 90 + 350);
      toast.success('Rating saved!');
    } catch {
      toast.error('Failed to save rating');
    }
  };

  const handleDelete = async () => {
    if (!queryId) return;
    setDeleting(true);
    // Wait for delete animation to complete
    await new Promise((r) => setTimeout(r, 320));
    try {
      await api.delete(`/query/${queryId}`);
      setDeleted(true);
      onDelete?.(queryId);
      toast.success('Query deleted');
    } catch {
      setDeleting(false);
      toast.error('Failed to delete query');
    }
  };

  // ── Render ───────────────────────────────────────────────────────

  return (
    <div className={`bg-dark-800 border border-dark-600 rounded-2xl overflow-hidden ${isNew ? 'response-new' : ''} ${deleting ? 'card-deleting' : ''}`}>
      {/* Header */}
      <div className="bg-dark-700 px-4 sm:px-5 py-3 flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-3 min-w-0">
          {/* AI badge */}
          <span className="shrink-0 px-1.5 py-0.5 rounded text-xs font-bold bg-gradient-to-r from-accent-purple to-accent-violet text-white leading-none">
            AI
          </span>
          <span className="px-2.5 py-0.5 rounded-full text-xs font-medium bg-accent-purple/20 text-accent-light border border-accent-purple/30 shrink-0">
            {subject}
          </span>
          <p className="text-slate-300 text-sm truncate">{question}</p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {/* Saved badge */}
          {showSavedBadge && (
            <span className="saved-badge flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-500/15 border border-green-500/25 text-green-400 text-xs font-medium">
              ✓ Saved
            </span>
          )}
          {/* Copy */}
          <button
            data-ripple
            onClick={handleCopy}
            aria-label="Copy answer to clipboard"
            title="Copy answer"
            className="px-2 py-1 rounded text-xs font-medium text-slate-400 hover:text-white hover:bg-dark-600 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-purple"
          >
            {copied ? '✓ Copied!' : 'Copy'}
          </button>
          {/* Share */}
          <button
            data-ripple
            onClick={handleShare}
            aria-label="Copy shareable text to clipboard"
            title="Share"
            className="px-2 py-1 rounded text-xs font-medium text-slate-400 hover:text-white hover:bg-dark-600 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-purple"
          >
            {shared ? '✓ Copied!' : 'Share'}
          </button>
          {/* Download */}
          <button
            data-ripple
            onClick={handleDownload}
            aria-label="Download answer as text file"
            title="Download as .txt"
            className="px-2 py-1 rounded text-xs font-medium text-slate-400 hover:text-white hover:bg-dark-600 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-purple"
          >
            ↓ Save
          </button>
          {/* Bookmark */}
          <button
            onClick={handleBookmark}
            disabled={loadingBookmark}
            aria-label={bookmarked ? 'Remove bookmark' : 'Bookmark this response'}
            title={bookmarked ? 'Remove bookmark' : 'Bookmark'}
            className={`text-lg transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-purple rounded ${
              bookmarked ? 'text-yellow-400' : 'text-slate-600 hover:text-yellow-400'
            }`}
          >
            <span className={starSpinning ? 'star-spin inline-block' : 'inline-block'}>
              {bookmarked ? '★' : '☆'}
            </span>
          </button>
          {/* Delete */}
          {showDelete && queryId && (
            <button
              onClick={handleDelete}
              aria-label="Delete this query"
              title="Delete"
              className="text-slate-600 hover:text-red-400 transition-colors text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-red-500 rounded"
            >
              🗑
            </button>
          )}
        </div>
      </div>

      {/* Original Response */}
      <div className="px-4 sm:px-5 py-4 prose-dark">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{response}</ReactMarkdown>
      </div>

      {/* Rating */}
      <div className="px-4 sm:px-5 py-3 border-t border-dark-600 flex items-center gap-2 flex-wrap">
        <span className="text-xs text-slate-500 mr-1">Rate this answer:</span>
        {[1, 2, 3, 4, 5].map((star) => {
          const isAnimating = animatingRating !== null && star <= animatingRating;
          return (
            <button
              key={star}
              onClick={() => handleRate(star)}
              aria-label={`Rate ${star} out of 5 stars`}
              className={`text-lg transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-purple rounded ${
                rating !== null && star <= rating ? 'text-yellow-400' : 'text-slate-700 hover:text-yellow-400'
              } ${isAnimating ? 'star-fill' : ''}`}
              style={isAnimating ? { animationDelay: `${(star - 1) * 80}ms` } : {}}
            >
              ★
            </button>
          );
        })}
        {rating && <span className="text-xs text-slate-500 ml-1">{rating}/5</span>}
      </div>

      {/* Follow-up Thread */}
      {followUps.length > 0 && (
        <div className="border-t border-dark-600">
          {followUps.map((fu, i) => (
            <div key={i} className="border-l-2 border-accent-purple/40 ml-4 sm:ml-6 my-4 mr-4 sm:mr-5 rounded-xl overflow-hidden">
              <div className="bg-dark-900/60 px-4 py-2.5 flex items-center gap-2">
                <span className="text-accent-purple text-xs font-semibold">↩ Follow-up {i + 1}</span>
                <span className="text-slate-500 text-xs truncate">{fu.question}</span>
              </div>
              <div className="bg-dark-900/40 px-4 py-3 prose-dark text-sm">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{fu.response}</ReactMarkdown>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Follow-up Input */}
      <div className="px-4 sm:px-5 py-3 border-t border-dark-600">
        <div className="flex gap-2 items-center">
          <input
            type="text"
            value={followUpInput}
            onChange={(e) => { setFollowUpInput(e.target.value); setFollowUpError(null); }}
            onKeyDown={handleFollowUpKeyDown}
            disabled={loadingFollowUp}
            placeholder="Ask a follow-up question about this topic..."
            aria-label="Follow-up question"
            className={`flex-1 bg-dark-700 border rounded-lg px-3 py-2 text-sm text-white placeholder-slate-600 focus:outline-none transition-colors disabled:opacity-50 ${
              followUpError ? 'border-red-500' : 'border-dark-500 focus:border-accent-purple'
            }`}
          />
          <button
            data-ripple
            onClick={handleFollowUp}
            disabled={loadingFollowUp || !followUpInput.trim()}
            aria-label="Submit follow-up question"
            className="shrink-0 px-3 py-2 rounded-lg bg-accent-purple hover:bg-accent-violet disabled:opacity-40 disabled:cursor-not-allowed text-white text-sm font-medium transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-purple"
          >
            {loadingFollowUp ? (
              <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
              </svg>
            ) : 'Ask'}
          </button>
        </div>
        {followUpError && <p className="text-red-400 text-xs mt-1.5">{followUpError}</p>}
        {followUps.length === 0 && (
          <p className="text-slate-600 text-xs mt-1.5">
            Press Enter to submit · Context from this answer is included automatically
          </p>
        )}
      </div>
    </div>
  );
}
